import { Language, TranslationSet, Location, LocationData } from "./types";

export const TUZLA_CENTER: [number, number] = [44.5388, 18.6750];

const LOCATIONS_RAW: Location[] = [
  {
    id: '1',
    name: {
      en: 'Pannonian Lakes',
      bs: 'Panonska jezera',
      de: 'Panonische Seen',
      tr: 'Pannonian Gölleri',
    },
    description: {
      en: 'The only salt lakes in Europe located in the city center. A unique complex of three lakes with medicinal properties.',
      bs: 'Jedina slana jezera u Evropi u centru grada. Jedinstven kompleks tri jezera sa ljekovitim svojstvima.',
      de: 'Die einzigen Salzseen in Europa direkt im Stadtzentrum. Einzigartiger Komplex aus drei Seen mit heilender Wirkung.',
      tr: 'Şehir merkezinde bulunan Avrupa\'nın tek tuz gölleri. Tıbbi özelliklere sahip üç gölden oluşan eşsiz bir kompleks.',
    },
    image: '/assets/Gallery/Pannonica-ljeto.webp',
    coordinates: [44.5385, 18.6767],
    category: 'nature',
    qrCode: 'Pannonian Lakes',
    discount: '10%',
  },
  {
    id: '2',
    name: {
      en: 'Old Town (Carsija)',
      bs: 'Stari grad (Carsija)',
      de: 'Altstadt (Carsija)',
      tr: 'Eski Şehir (Çarşı)',
    },
    description: {
      en: 'The historic heart of Tuzla with Ottoman architecture, cafes, and Freedom Square.',
      bs: 'Historijsko srce Tuzle sa otomanskom arhitekturom, kaficima i Trgom slobode.',
      de: 'Das historische Herz von Tuzla mit osmanischer Architektur, Cafes und dem Freiheitsplatz.',
      tr: 'Osmanlı mimarisi, kafeler ve Özgürlük Meydanı ile Tuzla\'nın tarihi kalbi.',
    },
    image: '/assets/Gallery/Square.webp',
    coordinates: [44.5391, 18.6750],
    category: 'culture',
    qrCode: 'Old Town',
    discount: '10%',
  },
  {
    id: '3',
    name: {
      en: 'Salt Square',
      bs: 'Trg soli',
      de: 'Salzplatz',
      tr: 'Tuz Meydanı',
    },
    description: {
      en: 'A square celebrating Tuzla s 2,500-year salt history with a replica salt well.',
      bs: 'Trg posvecen tuzlanskoj 2.500 godina dugoj historiji proizvodnje soli, sa replikom bunara za so.',
      de: 'Ein Platz, der Tuzlas 2.500-jahrige Geschichte der Salzgewinnung feiert, inklusive einer Replik eines Salzbrunnens.',
      tr: 'Tuzla\'nın 2.500 yıllık tuz tarihini bir tuz kuyusu kopyasıyla kutlayan bir meydan.',
    },
    image: '/assets/Gallery/SaltSquare.webp',
    coordinates: [44.5388, 18.6732],
    category: 'culture',
    qrCode: 'Salt Square',
    discount: 5,
  },
  {
    id: '4',
    name: {
      en: 'Ilincica Hill',
      bs: 'Brdo Ilincica',
      de: 'Ilincica Hugel',
      tr: 'İlinçica Tepesi',
    },
    description: {
      en: 'A popular recreational area offering a panoramic view of the city, perfect for hiking and picnics.',
      bs: 'Popularno izletiste sa panoramskim pogledom na grad, savrseno za planinarenje i piknike.',
      de: 'Ein beliebtes Naherholungsgebiet mit Panoramablick uber die Stadt, perfekt zum Wandern und Picknicken.',
      tr: 'Şehrin panoramik manzarasını sunan, yürüyüş ve piknik için mükemmel popüler bir dinlenme alanı.',
    },
    image: '/assets/Gallery/Ilincica.webp',
    coordinates: [44.5300, 18.6800],
    category: 'nature',
    qrCode: 'Ilincica Hill',
    discount: 'Health 100%',
  },
  {
    id: '5',
    name: {
      en: 'Tuzlanka Mall',
      bs: 'RK Tuzlanka',
      de: 'Tuzlanka Einkaufszentrum',
      tr: 'Tuzlanka Alışveriş Merkezi',
    },
    description: {
      en: 'One of the city s main shopping destinations with a variety of international and local brands.',
      bs: 'Jedna od glavnih shopping destinacija u gradu sa raznim medjunarodnim i lokalnim brendovima.',
      de: 'Eines der wichtigsten Einkaufsziele der Stadt mit vielen internationalen und lokalen Marken.',
      tr: 'Çeşitli uluslararası ve yerel markaların bulunduğu şehrin ana alışveriş noktalarından biri.',
    },
    image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&q=80&w=400',
    coordinates: [44.5381, 18.6650],
    category: 'shopping',
    qrCode: 'Tuzlanka Mall',
    discount: 10,
  },
  {
    id: 'mesa_selimovic',
    name: {
      en: 'Mesa Selimovic Statue',
      bs: 'Kip Meše Selimovića',
      de: 'Mesa-Selimovic-Statue',
      tr: 'Meşa Selimoviç Heykeli',
    },
    description: {
      en: 'Statue of the famous writer Mesa Selimovic.',
      bs: 'Kip poznatog pisca Meše Selimovica.',
      de: 'Statue des beruehmten Schriftstellers Mesa Selimovic.',
      tr: 'Ünlü yazar Meşa Selimoviç\'in heykeli.',
    },
    image: '/assets/Gallery/mesaselimovic.webp',
    coordinates: [44.5370993, 18.6781216],
    category: 'culture',
    qrCode: 'Mesa Selimovic',
    discount: 'Audio Reward',
  }
];

const BINGO_STORE_RAW = {
  name: 'Bingo Supermarket',
  address: 'Mitra Trifunovica Uce 2, Tuzla',
  rating: '100%',
  hours: {
    en: { monSat: '08:00 - 20:30', sun: 'Closed' },
    bs: { monSat: '08:00 - 20:30', sun: 'Zatvoreno' },
    de: { monSat: '08:00 - 20:30', sun: 'Geschlossen' },
    tr: { monSat: '08:00 - 20:30', sun: 'Kapalı' },
  },
  items: [
    { name: 'Fresh Fruit', price: 'Varies', image: '/assets/Gallery/Fruit.webp' },
    { name: 'Quality Meat', price: 'Varies', image: '/assets/Gallery/Meat.webp' },
    { name: 'Charcuterie', price: 'Varies', image: '/assets/Gallery/Charcuterie.webp' },
    { name: 'Vegetables & Herbs', price: 'Varies', image: '/assets/Gallery/Vegetables___Herbs.webp' },
  ],
};



const TRANSLATIONS_RAW: Record<Language, TranslationSet> = {
  en: {
    welcome: 'Welcome to Tuzla',
    history: 'History',
    map: 'Map',
    quest: 'Quest',
    gallery: 'Gallery',
    scanQr: 'Scan QR Code',
    rewardClaimed: 'Reward Unlocked!',
    discountMessage: 'You received a discount! Show this at the counter.',
    notificationTitle: 'Special Offer!',
    notificationBody: 'Pannonian Lakes price is now 5 EUR instead of 6 EUR today!',
    close: 'Close',
    viewOnMap: 'View on Map',
    foundAt: 'Found at',
    liveEvents: 'Live Events & News',
    wallet: 'Wallet',
    loginOAuth: 'Login with OAuth',
    touristInfo: 'Tourist Info',
    emergencyInfo: 'Emergency Info',
    bestSupermarket: 'Supermarket',
    workingHours: 'Working Hours',
    monSat: 'Mon - Sat',
    sunday: 'Sunday',
    closed: 'Closed',
    rating: 'Rating',
    reviews: 'Reviews',
    delivery: 'Delivery Available',
    noDelivery: 'No Delivery',
    typicalPrice: 'Typical Price',
    arGuide: 'AR Guide',
    walletManual: 'User Manual',
    howToConnect: 'How to Connect',
    connectSteps: "1. Click 'Connect Wallet'\n2. Open your TON wallet app\n3. Confirm in your app",
    safeUsage: 'Safe Usage',
    safeTips: '. Never share your phrase\n. Confirm every transaction\n. Use official TON apps only',
    txHistory: 'Where is history?',
    historyLocation: 'Transaction history is saved within your connected TON wallet app (Tonkeeper/MyTonWallet).',
    bamToEur: 'BAM - EUR Conversion',
    enterBam: 'Enter amount in BAM',
    calculatedEur: 'Equivalent in EUR',
    conversionRate: 'Rate: 1 BAM = 0.51 EUR (1:1.95583)',
    parking: 'SMS Parking',
    pannonicaAlt: 'Pannonica Lakes - Salt Lakes in Tuzla',
    pannonicaTitle: 'Welcome to Pannonica',
    pannonicaImage: '/assets/Pannonica.webp',
    parkingTitle: 'Parking',
    parkingActive: 'Active Parking',
    parkingAutoDetect: 'Auto Detect My Zone',
    parkingLicensePlate: 'License Plate',
    parkingHourly: 'Hourly',
    parkingDaily: 'Daily',
    parkingPaySms: 'Pay via SMS',
    parkingDetectNoZone: 'No parking zone detected.',
    parkingPromptPlate: 'Confirm zone and enter plate.',
    parkingPaymentInactive: 'Parking payment not active at this time.',
    parkingConfirm: 'Confirm',
    parkingCancel: 'Cancel',
    parkingDetected: 'Detected',
    trademarksDisclaimer: 'All logos and brand names are properties of their respective owners and are used here for informational/identification purposes only.',
    privacyNoticeTitle: 'Privacy & Camera Notice',
    privacyNoticeBody: 'This app uses your location solely for navigation to points of interest. The camera is activated only when you are within 10m of a destination to scan a QR code and trigger the AR guide. Your images and video feed are not stored or sent to any server; all processing occurs strictly on your device. By continuing, you consent to temporary access to these functions.',
    learnMore: 'Learn More',
    busStation: 'Bus Station',
    batteryWarning: 'Extreme Battery Saver Active. Lower brightness and use AR only when moving to preserve power.',
    selectNetwork: 'Select Network',
    solanaWallet: 'TON Wallet',
    tonWallet: 'TON Wallet',
    switchNetwork: 'Switch Network',
    connectedToSolana: 'Connected to TON',
  },
  bs: {
    welcome: 'Dobrodošli u Tuzlu',
    history: 'Historija',
    map: 'Mapa',
    quest: 'Potraga',
    gallery: 'Galerija',
    scanQr: 'Skeniraj QR Kod',
    rewardClaimed: 'Nagrada otključana!',
    discountMessage: 'Dobili ste popust! Pokazite ovo na kasi.',
    notificationTitle: 'Posebna ponuda!',
    notificationBody: 'Cijena Panonskih jezera danas je 5 EUR umjesto 6 EUR!',
    close: 'Zatvori',
    viewOnMap: 'Vidi na mapi',
    foundAt: 'Pronadjeno u',
    liveEvents: 'Dešavanja uživo i vijesti',
    wallet: 'Novčanik',
    loginOAuth: 'Prijava putem OAuth',
    touristInfo: 'Turističke informacije',
    emergencyInfo: 'Hitne informacije',
    bestSupermarket: 'Supermarket',
    workingHours: 'Radno vrijeme',
    monSat: 'Pon - Sub',
    sunday: 'Nedjelja',
    closed: 'Zatvoreno',
    rating: 'Ocjena',
    reviews: 'Recenzije',
    delivery: 'Dostava dostupna',
    noDelivery: 'Nema dostave',
    typicalPrice: 'Tipicna cijena',
    arGuide: 'AR Vodic',
    walletManual: 'Uputstvo za korištenje',
    howToConnect: 'Kako se povezati',
    connectSteps: "1. Kliknite 'Poveži novčanik'\n2. Otvorite TON aplikaciju\n3. Potvrdite u aplikaciji",
    safeUsage: 'Sigurno korištenje',
    safeTips: '. Nikad ne dijelite šifre\n. Potvrdite svaku transakciju\n. Koristite zvanične TON aplikacije',
    txHistory: 'Gdje je historija?',
    historyLocation: 'Historija transakcija se čuva u vašoj povezanoj TON aplikaciji (Tonkeeper/MyTonWallet).',
    bamToEur: 'Konverzija BAM - EUR',
    enterBam: 'Unesite iznos u BAM',
    calculatedEur: 'Iznos u EUR',
    conversionRate: 'Kurs: 1 BAM = 0.51 EUR (1:1.95583)',
    parking: 'SMS Parking',
    pannonicaAlt: 'Panonska jezera - Slana jezera u Tuzli',
    pannonicaTitle: 'Dobrodošli na Panoniku',
    pannonicaImage: '/assets/PannonicaBA.webp',
    parkingTitle: 'Parking',
    parkingActive: 'Aktivni parking',
    parkingAutoDetect: 'Automatski detektuj zonu',
    parkingLicensePlate: 'Registarska oznaka',
    parkingHourly: 'Satni',
    parkingDaily: 'Dnevni',
    parkingPaySms: 'Plati putem SMS-a',
    parkingDetectNoZone: 'Parking zona nije detektovana.',
    parkingPromptPlate: 'Potvrdite zonu i unesite registraciju.',
    parkingPaymentInactive: 'Placanje parkinga trenutno nije aktivno.',
    parkingConfirm: 'Potvrdi',
    parkingCancel: 'Ponisti',
    parkingDetected: 'Detektovano',
    trademarksDisclaimer: 'Svi logotipi i nazivi brendova su vlasnistvo njihovih vlasnika i koriste se ovdje iskljucivo u informativne svrhe.',
    privacyNoticeTitle: 'Obavjestenje o privatnosti i kameri',
    privacyNoticeBody: 'Ova aplikacija koristi vasu lokaciju iskljucivo za navigaciju do znamenitosti. Kamera se aktivira samo kada ste u neposrednoj blizini (10m) od cilja kako biste skenirali QR kod i pokrenuli AR vodic. Vasa slika i video zapis se ne pohranjuju niti salju na server; sva obrada se vrsi iskljucivo na vasem uredaju. Nastavkom koristenja pristajete na privremeni pristup ovim funkcijama.',
    learnMore: 'Saznajte više',
    busStation: 'Autobuska Stanica Tuzla',
    batteryWarning: 'Štednja baterije aktivna. Smanjite svjetlinu i koristite AR vodic samo u pokretu za duže trajanje.',
    selectNetwork: 'Odaberi mrežu',
    solanaWallet: 'TON novčanik',
    tonWallet: 'TON novčanik',
    switchNetwork: 'Promijeni mrežu',
    connectedToSolana: 'Povezan na TON',
  },
  de: {
    welcome: 'Willkommen in Tuzla!',
    history: 'Geschichte',
    map: 'Karte',
    quest: 'Quest',
    gallery: 'Galerie',
    scanQr: 'QR-Code scannen',
    rewardClaimed: 'Belohnung freigeschaltet!',
    discountMessage: 'Du hast einen Rabatt bekommen! Zeig das einfach an der Kasse vor.',
    notificationTitle: 'Sonderangebot!',
    notificationBody: 'Die Panonischen Seen kosten heute nur 5 EUR statt 6 EUR!',
    close: 'Schliessen',
    viewOnMap: 'Auf der Karte ansehen',
    foundAt: 'Gefunden bei',
    liveEvents: 'Live-Events & News',
    wallet: 'Wallet',
    loginOAuth: 'Login mit OAuth',
    touristInfo: 'Tourist Info',
    emergencyInfo: 'Notfall-Infos',
    bestSupermarket: 'Bester Supermarkt',
    workingHours: 'Offnungszeiten',
    monSat: 'Mo - Sa',
    sunday: 'Sonntag',
    closed: 'Geschlossen',
    rating: 'Bewertung',
    reviews: 'Bewertungen',
    delivery: 'Lieferung moglich',
    noDelivery: 'Keine Lieferung',
    typicalPrice: 'Normaler Preis',
    arGuide: 'AR-Guide',
    walletManual: 'Bedienungsanleitung',
    howToConnect: 'So verbindest du dich',
    connectSteps: "1. Klick auf 'Wallet verbinden'\n2. Öffne deine TON Wallet App\n3. Bestätige alles in deiner App",
    safeUsage: 'Sicherheitstipps',
    safeTips: '. Teil niemals deine Recovery Phrase\n. Bestatige jede Transaktion einzeln\n. Nutze nur offizielle TON Apps',
    txHistory: 'Wo ist der Verlauf?',
    historyLocation: 'Dein Transaktionsverlauf wird direkt in deiner TON Wallet App (Tonkeeper/MyTonWallet) gespeichert.',
    bamToEur: 'BAM - EUR Umrechner',
    enterBam: 'Betrag in BAM eingeben',
    calculatedEur: 'Gegenwert in EUR',
    conversionRate: 'Kurs: 1 BAM = 0.51 EUR (1:1.95583)',
    parking: 'SMS Parking',
    pannonicaAlt: 'Panonische Seen - Salzseen in Tuzla',
    pannonicaTitle: 'Willkommen an der Panonica',
    pannonicaImage: '/assets/PannonicaDE.webp',
    parkingTitle: 'Parken',
    parkingActive: 'Aktives Parkticket',
    parkingAutoDetect: 'Zone automatisch erkennen',
    parkingLicensePlate: 'Kennzeichen',
    parkingHourly: 'Stundlich',
    parkingDaily: 'Tagesticket',
    parkingPaySms: 'Per SMS bezahlen',
    parkingDetectNoZone: 'Keine Parkzone erkannt.',
    parkingPromptPlate: 'Zone bestatigen und Kennzeichen eingeben.',
    parkingPaymentInactive: 'Parkgebuhren sind gerade nicht aktiv.',
    parkingConfirm: 'Bestatigen',
    parkingCancel: 'Abbrechen',
    parkingDetected: 'Erkannt',
    trademarksDisclaimer: 'Alle Logos und Markennamen sind Eigentum ihrer jeweiligen Inhaber und werden hier nur zu Informations-/Identifikationszwecken verwendet.',
    privacyNoticeTitle: 'Datenschutz- und Kamerahinweis',
    privacyNoticeBody: 'Diese App verwendet Ihren Standort ausschliesslich zur Navigation zu Sehenswurdigkeiten. Die Kamera wird nur aktiviert, wenn Sie sich im Umkreis von 10m von einem Ziel befinden, um einen QR-Code zu scannen und den AR-Guide zu starten. Ihre Bilder und Video-Feeds werden weder gespeichert noch an Server gesendet; die gesamte Verarbeitung erfolgt ausschliesslich auf Ihrem Gerat. Mit der weiteren Nutzung stimmen Sie dem vorubergehenden Zugriff auf diese Funktionen zu.',
    learnMore: 'Mehr erfahren',
    busStation: 'Busbahnhof',
    batteryWarning: 'Extremer Energiesparmodus aktiv. Helligkeit senken und AR nur bei Bewegung nutzen.',
    selectNetwork: 'Netzwerk wählen',
    solanaWallet: 'TON Wallet',
    tonWallet: 'TON Wallet',
    switchNetwork: 'Netzwerk wechseln',
    connectedToSolana: 'Mit TON verbunden',
  },
  tr: {
    welcome: 'Tuzla\'ya Hoşgeldiniz',
    history: 'Tarih',
    map: 'Harita',
    quest: 'Görev',
    gallery: 'Galeri',
    scanQr: 'QR Kodunu Tara',
    rewardClaimed: 'Ödül Açıldı!',
    discountMessage: 'Bir indirim kazandınız! Bunu kasada gösterin.',
    notificationTitle: 'Özel Teklif!',
    notificationBody: 'Pannonian Gölleri fiyatı bugün 6 EUR yerine 5 EUR!',
    close: 'Kapat',
    viewOnMap: 'Haritada Gör',
    foundAt: 'Bulundu',
    liveEvents: 'Canlı Etkinlikler ve Haberler',
    wallet: 'Cüzdan',
    loginOAuth: 'OAuth ile Giriş Yap',
    touristInfo: 'Turist Bilgisi',
    emergencyInfo: 'Acil Durum Bilgisi',
    bestSupermarket: 'Süpermarket',
    workingHours: 'Çalışma Saatleri',
    monSat: 'Pzt - Cmt',
    sunday: 'Pazar',
    closed: 'Kapalı',
    rating: 'Değerlendirme',
    reviews: 'Yorumlar',
    delivery: 'Teslimat Var',
    noDelivery: 'Teslimat Yok',
    typicalPrice: 'Tipik Fiyat',
    arGuide: 'AR Rehberi',
    walletManual: 'Kullanım Kılavuzu',
    howToConnect: 'Nasıl Bağlanılır',
    connectSteps: "1. 'Cüzdanı Bağla'ya tıklayın\n2. TON cüzdanını açın\n3. Uygulamada onaylayın",
    safeUsage: 'Güvenli Kullanım',
    safeTips: '. Şifrenizi asla paylaşmayın\n. Her işlemi onaylayın\n. Yalnızca resmi TON uygulamalarını kullanın',
    txHistory: 'Geçmiş nerede?',
    historyLocation: 'İşlem geçmişi bağlı TON cüzdanınıza (Tonkeeper/MyTonWallet) kaydedilir.',
    bamToEur: 'BAM - EUR Çevrimi',
    enterBam: 'BAM miktarını girin',
    calculatedEur: 'EUR karşılığı',
    conversionRate: 'Kur: 1 BAM = 0.51 EUR (1:1.95583)',
    parking: 'SMS Otopark',
    pannonicaAlt: 'Pannonica Gölleri - Tuzla\'daki Tuz Gölleri',
    pannonicaTitle: 'Pannonica\'ya Hoşgeldiniz',
    pannonicaImage: '/assets/Pannonica.webp',
    parkingTitle: 'Otopark',
    parkingActive: 'Aktif Otopark',
    parkingAutoDetect: 'Bölgemi Otomatik Algıla',
    parkingLicensePlate: 'Plaka',
    parkingHourly: 'Saatlik',
    parkingDaily: 'Günlük',
    parkingPaySms: 'SMS ile Öde',
    parkingDetectNoZone: 'Otopark bölgesi algılanmadı.',
    parkingPromptPlate: 'Bölgeyi onaylayın ve plakayı girin.',
    parkingPaymentInactive: 'Otopark ödemesi şu anda aktif değil.',
    parkingConfirm: 'Onayla',
    parkingCancel: 'İptal',
    parkingDetected: 'Algılandı',
    trademarksDisclaimer: 'Tüm logolar ve marka isimleri ilgili sahiplerinin mülkiyetindedir ve burada yalnızca bilgi/tanımlama amacıyla kullanılmıştır.',
    privacyNoticeTitle: 'Gizlilik ve Kamera Bildirimi',
    privacyNoticeBody: 'Bu uygulama konumunuzu yalnızca önemli noktalara navigasyon için kullanır. Kamera yalnızca bir hedefe 10m yaklaştığınızda QR kodunu taramak ve AR rehberini başlatmak için etkinleştirilir. Resimleriniz ve video akışınız kaydedilmez veya herhangi bir sunucuya gönderilmez; tüm işlemler yalnızca cihazınızda gerçekleşir. Devam ederek, bu işlevlere geçici erişime izin vermiş olursunuz.',
    learnMore: 'Daha Fazla Bilgi',
    busStation: 'Otobüs Durağı',
    batteryWarning: 'Ekstra Pil Tasarrufu Aktif. Güç tasarrufu için parlaklığı düşürün ve ARyı sadece hareket halindeyken kullanın.',
    selectNetwork: 'Ağ Seçin',
    solanaWallet: 'TON Cüzdanı',
    tonWallet: 'TON Cüzdanı',
    switchNetwork: 'Ağı Değiştir',
    connectedToSolana: 'TON\'a Bağlı',
  },
};

const RESTAURANTS_RAW = [
  {
    name: 'Taco Bell',
    address: 'Univerzitetska 16 (Tuzlanka Mall)',
    type: { en: 'Mexican Fast Food', bs: 'Meksicka brza hrana', de: 'Mexikanisches Fast Food', tr: 'Meksika Fast Food' },
    price: '9-18 KM',
    image: '/assets/Gallery/tacobellqr.jpeg',
  },
  {
    name: 'Pekara Hukic',
    address: 'Gradska 59, Tuzla',
    type: { en: 'Traditional Bakery & Pizza', bs: 'Tradicionalna pekara i pizza', de: 'Traditionelle Backerei & Pizza', tr: 'Geleneksel Fırın ve Pizza' },
    price: '3-17 KM',
    image: '/assets/Gallery/Food/hukic.webp',
  },
  {
    name: 'Palacinkara kod Bagija',
    address: 'Patriotske lige 10, Tuzla',
    type: { en: 'Famous Sweet & Sushi Pancakes', bs: 'Poznate slatke i sushi palacinke', de: 'Legendare suse Pfannkuchen & Pancake-Sushi', tr: 'Ünlü Tatlı ve Suşi Krepleri' },
    price: '3-9 KM',
    image: '/assets/Gallery/bagi.webp',
  },
  {
    name: 'Libero Caffe',
    address: 'Armije Republike BiH 17, Tuzla',
    type: { en: 'Vibrant Social Hub & Italian Food', bs: 'Popularni caffe i italijanska hrana', de: 'Vibranter Social Hub & italienisches Essen', tr: 'Canlı Sosyal Merkez ve İtalyan Yemekleri' },
    price: '7-15 KM',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=400',
  },
  {
    name: 'Choco Loco',
    address: 'Solni trg / Prekinute mladosti 10, Tuzla',
    type: { en: 'Rich Cakes & Turkish Lokma', bs: 'Bogati kolaci i turske lokme', de: 'Kuchen & Lokma', tr: 'Zengin Pastalar ve Türk Lokması' },
    price: '3-7 KM',
    image: '/assets/Gallery/chocoloco.webp',
  },
  {
    name: 'Nota Bene Pizzeria',
    address: 'I inzinjerske brigade, Tuzla',
    type: { en: 'Quality Italian Pizza & Breakfast', bs: 'Kvalitetna italijanska pizza i dorucak', de: 'Italienische Pizza & Fruhstuck', tr: 'Kaliteli İtalyan Pizzası ve Kahvaltı' },
    price: '6-10 KM',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=400',
  },
];

export const TUZLA_DINING_DATA: LocationData[] = [
  {
    name: 'Taco Bell Tuzla',
    rating: 4.3,
    user_ratings_total: 189,
    address: 'Univerzitetska 16, Tuzla',
    latitude: 44.538497,
    longitude: 18.664660,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/taco.webp',
  },
  {
    name: 'Pekara Hukic',
    rating: 4.6,
    user_ratings_total: 410,
    address: 'ZAVNOBiH-a 7, Tuzla',
    latitude: 44.539990,
    longitude: 18.673059,
    category: 'Bakery',
    type: 'Dining',
    image: '/assets/Gallery/Food/hukic.webp',
  },
  {
    name: 'Libero Caffe',
    rating: 4.5,
    user_ratings_total: 278,
    address: 'Armije Republike Bosne i Hercegovine 17, Tuzla',
    latitude: 44.542283,
    longitude: 18.693450,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/bosna.webp',
  },
  {
    name: 'Nota Bene Pizzeria',
    rating: 4.8,
    user_ratings_total: 320,
    address: 'I inzinjerske brigade bb, Tuzla',
    latitude: 44.534160,
    longitude: 18.698330,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/envie.webp',
  },
  {
    name: 'Mozaik',
    rating: 4.7,
    user_ratings_total: 493,
    address: 'Turalibegova 2, Tuzla',
    latitude: 44.537233,
    longitude: 18.674936,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/mozaik.webp',
  },
  {
    name: 'Pizza Trkacica',
    rating: 4.9,
    user_ratings_total: 211,
    address: 'Setaliste Slana Banja, Tuzla',
    latitude: 44.525767,
    longitude: 18.696539,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/pizza.webp',
  },
  {
    name: 'Fast Food King',
    rating: 4.9,
    user_ratings_total: 257,
    address: 'GMMW+9R6 Trzni Centar, Tuzla',
    latitude: 44.53721,
    longitude: 18.67817,
    category: 'Fast Food',
    type: 'Dining',
    image: '/assets/Gallery/Food/smashbosbur.webp',
  },
  {
    name: 'Sezam Tennis',
    rating: 4.9,
    user_ratings_total: 59,
    address: 'Nesiba Malkica 20, Tuzla',
    latitude: 44.538717,
    longitude: 18.676906,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/foodprime.webp',
  },
  {
    name: 'Pizzeria La Linea',
    rating: 4.9,
    user_ratings_total: 47,
    address: 'Stupine B2, Tuzla',
    latitude: 44.531200,
    longitude: 18.688800,
    category: 'Restaurant',
    type: 'Dining',
    image: '/assets/Gallery/Food/cevapibrajlovic.webp',
  },
];

export const ALL_TUZLA_VENUES = TUZLA_DINING_DATA;

export const LOCATIONS = LOCATIONS_RAW;
export const BINGO_STORE = BINGO_STORE_RAW;
export const TRANSLATIONS: Record<Language, TranslationSet> = TRANSLATIONS_RAW;
export const RESTAURANTS = RESTAURANTS_RAW;
